version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
    timezone: America/Sao_Paulo
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.fasterxml.jackson:jackson-bom
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.asynchttpclient:async-http-client
    versions:
    - 2.12.2
  - dependency-name: org.codehaus.mojo:animal-sniffer-enforcer-rule
    versions:
    - "1.19"
